server:
  port: 8050
  
spring:
  application:
    name: cloud-api-gateway
  cloud:
    gateway:
      routes:
      - id: Crop-Management
        uri: lb://Crop-Management
        predicates:
        - Path=/crop/**
      - id: Farmer-Management
        uri: lb://Farmer-Management
        predicates:
        - Path=/farmer/**
      - id: Dealer-Management
        uri: lb://Dealer-Management
        predicates:
        - Path=/dealer/**
      - id: Payment-Management
        uri: lb://Payment-Management
        predicates:
        - Path=/payment/**
      
        
        
            
 